name: buildfork
on:
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Cache
       uses: actions/cache@v4.0.0
       with:
        path: ~/.npm
        key: buildCache
 
